runtime: python27
api_version: 1
threadsafe: yes

builtins:
  - appstats: on
  - deferred: on
  - remote_api: on

inbound_services:
  - warmup

libraries:
  - name: ssl
    version: latest

handlers:

- url: /js
  static_dir: dist/js

- url: /css
  static_dir: dist/css

- url: /.*
  script: main.app
  secure: always
