runtime: python27
api_version: 1
threadsafe: yes

builtins:
  - appstats: on
  - deferred: on
  - remote_api: on

inbound_services:
  - warmup

libraries:
  - name: ssl
    version: latest
  
handlers:

- url: /static
  static_dir: static/

- url: /.*
  script: main.app
  secure: always



